# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help

name: pkgdown
on: {
  push: {branches: [main, master, fix-actions]},
  pull_request: {branches: [main, master, fix-actions]},
  release: {types: [published]},
  workflow_dispatch: {}
}

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with: {use-public-rspm: true}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with: { extra-packages: "any::pkgdown, local::.", needs: website }

      # - name: Install R dev packages
      #   run: sudo Rscript misc/scripts/install-r-dev-pkgs.R

      # - name: Run R CMD javareconf
      #   run: sudo R CMD javareconf

      # - name: Install R Java
      #   run: sudo Rscript misc/scripts/install-rjava.R

      # - name: Install FastRet
      #   run: sudo Rscript misc/scripts/install-fastret.R --branch fix-actions --verbose

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      - name: Deploy to GitHub pages
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with: { clean: false, branch: gh-pages, folder: docs }
