
# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help

name: r-cmd-check
on: {
  push: {branches: [main, master]},
  pull_request: {branches: [main, master]}
}

jobs:
  r-cmd-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,    r: 'release', extra-packages: 'any::rcmdcheck any::xgboost'}
          - {os: windows-latest,  r: 'release', extra-packages: 'any::rcmdcheck any::xgboost'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release', extra-packages: 'any::rcmdcheck any::xgboost'}
          - {os: ubuntu-latest,   r: 'release', extra-packages: 'any::rcmdcheck any::xgboost'}
          - {os: ubuntu-latest,   r: 'oldrel-1', extra-packages: 'any::rcmdcheck any::xgboost'}
          - {os: ubuntu-latest,   r: '4.1', extra-packages: 'any::rcmdcheck any::xgboost@1.7.7.1'}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Set up R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: ${{ matrix.config.extra-packages }}
          needs: "check"

      - name: Test FastRet
        uses: r-lib/actions/check-r-package@v2
